# Generated by Django 4.0.10 on 2024-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_cinemas',
            field=models.ManyToManyField(blank=True, to='rest_api.cinema'),
        ),
    ]
