# Generated by Django 4.0.10 on 2024-03-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
